# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/1c668010-ad46-4b7e-95ad-fac948a55a72";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/2f7b07ca-fdee-4e6a-8b82-a3e988a7a7e4";

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/C5A9-B171";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/36d39342-e9f5-47f6-8f14-e3376eabc9ed";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."crypthome".device = "/dev/disk/by-uuid/f2e001d4-0cb7-4850-bcad-83c8bd0ed97f";

  swapDevices = [
    {device = "/dev/disk/by-uuid/f475bf83-33b3-4997-ad53-7cacbeccd9f4";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
